FROM ubuntu as build

# Update the package index and install essential packages
RUN apt-get update && \
    apt-get install -y iproute2 sudo git python3-pip python3 coreutils net-tools tcpdump vim tmux openssh-server ruby-dev python3 python3-pip iputils-ping build-essential

RUN pip3 install pexpect
# Copy your internal.py file to the container
COPY internal.py /internal.py
RUN python3 --version

