version: '3'
services:
  icmptunnel-client:
    container_name: icmptunnel-client
    build:
      context: .
      dockerfile: dockerfile-client
    command: sleep 10000
    networks:
      - icmp_test
    tty: true

  icmptunnel-server:
    container_name: icmptunnel-server
    build: 
      context: .
      dockerfile: dockerfile-server
    command: sleep 10000
    networks:
      - icmp_test
    tty: true

networks:
  icmp_test:
    driver: bridge