FROM ubuntu as build

# Update the package index and install essential packages
RUN apt-get update && \
    apt-get install -y iproute2 sudo git python3 python3-pip coreutils net-tools tcpdump vim tmux ruby-dev openssh-server iputils-ping build-essential

RUN pip3 install pexpect
# Copy your internal.py file to the container
COPY internal.py /internal.py
RUN python3 --version


